# 1. Array Creation Functions

In [1]:
import numpy as np

In [4]:
# Create an array from the list 
a = np.array([1, 2, 3])
print("Array a:", a)

Array a: [1 2 3]


In [6]:
# Create an array with even spaced value 
a = np.arange(0,10,2) # Values from o to 10 with step 2 
print("Array b:", b)


Array b: [0 2 4 6 8]


In [7]:
# Create an array with odd spaced value 
b = np.arange(0,10,3) # Values from o to 10 with step 2 
print("Array b:", b)


Array b: [0 3 6 9]


In [9]:
# Create an array with filled with zeros 
d = np.zeros((2,3), dtype=int) # 2 X 3 array of zeros 
print("Array d:\n", d)

Array d:
 [[0 0 0]
 [0 0 0]]


In [15]:
# Create an array with filled with ones  
e= np.ones((2,3), dtype =int) # 2 X 3 array of zeros 
print("Array e:\n", e)

Array e:
 [[1 1 1]
 [1 1 1]]


In [16]:
# create an identify matrix 
f = np.eye(4) # 4 X 4 Identity matrix = diagonals are 1 
print("IDeNTITY matrix f:\n", f)



IDeNTITY matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# 2. Array Mainpulation Functions

In [19]:
# Reshaping an array 
a1 = np.array([1, 2, 3])
reshaped = np.reshape(a1,(1,3)) # Reshape to 1 X 3 
print("Reshaped array:", reshaped)

Reshaped array: [[1 2 3]]


In [104]:
# Flatten an array 
# Flattened to one d array , merge 2 arrays to one array 
f1 = np.array([[1, 2], [3,4]])
flattened = np.ravel(f1) # Flatten to 1D Array 
print("Flattened array:", flattened)
a.flatten()


Flattened array: [1 2 3 4]


array([1, 2, 3])

In [23]:
# Transpose of an array 
# Convert rows to columns and columns to rows

e1 = np.array([[1,2],[3,4]])
transposed = np.transpose(e1) # Transpose the array 
print( " Transposed array:\n", transposed)


 Transposed array:
 [[1 3]
 [2 4]]


In [24]:
# Stack array vertically 

a2 = np.array([1,2])
b2 = np.array([3,4])
stacked = np.vstack([a2,b2]) # stack a nad b vertically 
print("Stacked arrays:\n", stacked)

Stacked arrays:
 [[1 2]
 [3 4]]


In [28]:
# Stack array horizontally  

a3 = np.array([1,2])
b3 = np.array([3,4])
stacked = np.hstack([a3,b3]) # stack a nad b vertically 
print("Stacked arrays:\n", stacked)

Stacked arrays:
 [1 2 3 4]


# 3. Mathematical Functions

In [29]:
# Add two arrays 
g = np.array([1, 2, 3, 4])
added = np.add(g,2) # Add 2 to each element 
print("Added 2 to g:", added)

Added 2 to g: [3 4 5 6]


In [30]:
# Square each element 
squared = np.power(g,2) # Square each element 
print("Squared g:", squared)



Squared g: [ 1  4  9 16]


In [31]:
# cube each element 
cubed = np.power(g,3) # Square each element 
print("Cubed g:", cubed)


Cubed g: [ 1  8 27 64]


In [33]:
# square root of each element 
sqrt_val1 = np.sqrt(g) # Square root of each element 
print("Square root of g:", sqrt_val1)

Square root of g: [1.         1.41421356 1.73205081 2.        ]


In [34]:
print(a1)
print(g)

[1 2 3]
[1 2 3 4]


In [38]:
a = a1

print(a1)

[1 2 3]


In [40]:
# Dot product of two arrays --- Multiply the matrices
a2 = np.array([1,2,3])
dot_product = np.dot(a1,a) # Dot product of a and a1 
print("Dot product of a1 and a:", dot_product )


Dot product of a1 and a: 14


In [41]:
g

array([1, 2, 3, 4])

In [43]:
# Dot product of two arrays --- Multiply the matrices
a2 = np.array([1,2,3])
dot_product = np.dot(a2,g) # Dot product of a and a1 
print("Dot product of a1 and a:", dot_product )

# Make sure the shape should be match meaning same dimensions



ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

# 4. Statistical Functions 

In [44]:
# Find mean
s = np.array([1, 2, 3, 4])
mean = np.mean(s)
print("Mean of s:", mean) # find mean , average

Mean of s: 2.5


In [105]:
# Finding Variants ----- (x1-mean)square+..../totale 
# Variance i sthe measure of how far a set of numbers are spread out from their average value
s = np.array([1,2,3,4]) 
vars = np.var(s)
print("Variants;", vars)


Variants; 1.25


In [47]:
# Finding standard deviation  ----- (x1-mean)square+..../totale
# Standard deviation is a measure of the amount of variation or dispersion of a set of values.
s = np.array([1,2,3,4]) 
std = np.std(s)
print("Standard deviation;", std)


Standard deviation; 1.118033988749895


In [49]:
# Finding Minimum element of an array 
Minimum = np.min(s)
print("Min of s:", Minimum)

Min of s: 1


In [50]:
# Maximum element of an array 
maximum = np.max(s)
print("Max of s:", maximum)

Max of s: 4


# 5. Linear algebra functions 

In [ ]:
# Create a matrix


# Random Sampling functions 

In [51]:
# Population means entire globe 
# Sample means a country 
# Random Sample means the probability 
# Generate random values between 0 and 1 

random_vals = np.random.rand(3) # Array of 3 random values between 0 and 1 
print("Random values:", random_vals)


Random values: [0.12125303 0.37175067 0.05862856]


In [92]:
# Set seed for reproductibility 
np.random.seed(0) # Makes the np.random fixed (deterministic)
                    # parameter (0) is mandatory
# Generate random values between 0 and 1

random_vals = np.random.rand(3) # Array of 3 random values between 0 and 1
print("Random Values:", random_vals)

Random Values: [0.5488135  0.71518937 0.60276338]


In [63]:
# Generate random integers
rand_ints = np.random.randint(0, 10, size=5) # Random integers between 0 and 10
print("Random integers:", rand_ints)

Random integers: [9 6 9 1 7]


# 7. Boolean and logical functions

In [93]:
# check if all elements are true 
logical_test = np.array([True, False, True])
all_true = np.all(logical_test) # Check if all are True 
print(" All elements True:", all_true )

 All elements True: False


In [94]:
# Check if any elements are true 
logical_test = np.array([True, False, True])
any_true = np.any(logical_test) # Check if all are True 
print(" Any elements True:", any_true )

 Any elements True: True


# 8. Set Operations 

In [95]:
# Intersection of two arrays 
set_a = np.array([1, 2, 3, 4])
set_b = np.array([3, 4, 5, 6])
intersection = np.intersect1d(set_a, set_b)
print("Intersection of a and b:", intersection)


Intersection of a and b: [3 4]


In [96]:
# Union of two arrays 
union = np.union1d(set_a, set_b)
print("union of a nad b:", union)

union of a nad b: [1 2 3 4 5 6]


# 9. Array Attribute Functions 

In [98]:
# Array Attribute 
a = np.array([1,2,3])
shape = a.shape # Shape of the array 
size = a.size # Number of elements 
dimensions = a.ndim # Number of dimensions 
dtype = a.dtype # Data type of elements

print("Shape of a:", shape)
print("Size of a:", size)
print("Dimensions of a:", dimensions)
print("Data type of a:", dtype)



Shape of a: (3,)
Size of a: 3
Dimensions of a: 1
Data type of a: int64


# 10. Other Functions 

In [99]:
# Create a copy of an array
a = np.array([1, 2, 3])
copied_array = np.copy(a)  # Create a copy of array a
print("Copied array:", copied_array)

Copied array: [1 2 3]


In [100]:
# Size in bytes of an array
array_size_in_bytes = a.nbytes  # Size in bytes
print("Size of a in bytes:", array_size_in_bytes)

Size of a in bytes: 24


In [101]:
# Check if two arrays share memory
shared = np.shares_memory(a, copied_array)  # Check if arrays share memory
print("Do a and copied_array share memory?", shared)

Do a and copied_array share memory? False


In [102]:
np.linspace(0, 1, 5)         # 5 evenly spaced values between 0 an 1


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [103]:
np.full((2, 2), 7)           # fill with constant

array([[7, 7],
       [7, 7]])