# Numpy 

1. Numpy is the (package = library) which handles nd array(n-dimension array)

2. Numpy is used in data analysis, business analysis, data science,

3. Numpy is an opesource 

Numpy will be implemented in 
1. Arithmetic Operation 
2. statistic Operation
3. bitwise operation
4. copy & view array 
5. stacking 
6. searching, sorting, counting
7. math operation
8. broadcasting

data Structure --  Collections of data types 
array -- collection of data structure 
tensor -- collection of array 
dataframe -- collection of rows & Columns 


In [2]:
import numpy as np # Importing numpy alias as np 

In [ ]:
np.__version__ # Output will be numpy version which 2.4.1 

'2.4.1'

In [ ]:
import sys 
sys.version # System version 

'3.11.14 (main, Oct 21 2025, 18:27:30) [Clang 20.1.8 ]'

# Creating Arrays 

In [6]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [7]:
type(my_list)

list

In [8]:
arr = np.array(my_list)

In [9]:
arr 

array([0, 1, 2, 3, 4, 5])

In [10]:
type(arr)

numpy.ndarray

In [11]:
type(my_list)

list

In [12]:
np.    #displays all available functions in numpy sucha as arange, ones and .... 

SyntaxError: invalid syntax (2159955957.py, line 1)

In [13]:
np.arange(15) # Generates an array with range 0 to 15 (exclusive)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
np.arange(3.0)

array([0., 1., 2.])

In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(10,20) # displays output with range 10(inclusive) and 20 (exclusive)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [20]:
np.arange(20,10) # 1st arg < 2nd arg throws error 

array([], dtype=int64)

In [21]:
np.arange(-20,10) 


array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [23]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [24]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [25]:
np.arange(30,20) # 1st arg always be < then 2nd arg 


array([], dtype=int64)

In [26]:
ar = np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [27]:
np.arange(10,10)

array([], dtype=int64)

In [ ]:
np.arange() # we should specify the stopping point in array 

TypeError: arange() requires stop to be specified.

In [ ]:
np.arange(10,30,5) # 10(inclusive) is starting point,30(exclusive) ending point and 5 step count . 

array([10, 15, 20, 25])

In [30]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [34]:
np.arange(10,30,5,8) # 8 is not a valid data type as the fourth arg is datatype which is currently 8 
                    # by default none

TypeError: Cannot interpret '8' as a data type

In [ ]:
np.arange(10,30,5,dtype = int) # valid 

array([10, 15, 20, 25])

In [35]:
np.zeros(3) # parameter tuning 

array([0., 0., 0.])

In [37]:
np.zeros(5, dtype = int) # hyperparameter tuning

array([0, 0, 0, 0, 0])

In [38]:
np.zeros((2,2), dtype = int)

array([[0, 0],
       [0, 0]])

In [ ]:
zero = np.zeros([2,2]) # prints a 2 x 2 array first 2 is row and second 2 is column
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [ ]:
np.zeros((2,10))# prints a 2 rows X 10 columns array 

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [41]:
np.zeros((2,2)) # prints a 2 row X 2 column of zeros

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.zeros((3,3)) # prints a 3 row X 3 column array 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [44]:
np.zeros((10,30)) # prints a 10 row X 30 column array 

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [45]:
np.zeros((5,10)) # bydefault 1st arg will row and 2nd arg will columns 

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
n = (6,7)
n1 = (6,8)
print(np.zeros(n1)) # parameter tuning as by default dtype = none and it will print in float

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
print(np.zeros(n,dtype = int)) ## hyperparameter tuning now changed it to dtype = int

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [50]:
print(n)
print(n1)

(6, 7)
(6, 8)


In [51]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
np.ones(3) # prints an array with 1's and length of the array is 3 and datatype is float as default is none

array([1., 1., 1.])

In [56]:
np.ones(4)

array([1., 1., 1., 1.])

In [55]:
np.ones(4, dtype = int)# prints an array with 1's and length of the array is  and datatype is int

array([1, 1, 1, 1])

In [57]:
n

(6, 7)

In [58]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [60]:
np.ones((5,4),dtype = int) # by default 5 rows and 4 columns 

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [61]:
np.

SyntaxError: invalid syntax (2469254449.py, line 1)

In [ ]:
np.twos ((2,3)) # does not work like ones and zeros as it is not a valid function 

AttributeError: module 'numpy' has no attribute 'twos'

In [ ]:
np.three(2,3) # same as above 

AttributeError: module 'numpy' has no attribute 'three'

In [64]:
np.ones(2)

array([1., 1.])

In [65]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [66]:
np.ones((6,10), dtype = int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [67]:
np.twos((2,4))

AttributeError: module 'numpy' has no attribute 'twos'

In [68]:
range(5)

range(0, 5)

In [70]:
r = range(5)
r

range(0, 5)

In [71]:
for i in r: 
    print(i)

0
1
2
3
4


In [72]:
list(range(5))

[0, 1, 2, 3, 4]

In [73]:
range(1,10)

range(1, 10)

In [74]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [75]:
list(range(1,10,3))

[1, 4, 7]

In [76]:
y = list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [78]:
rand(3,2)
random.rand(3,2)

NameError: name 'rand' is not defined

In [79]:
np.random.rand(5)

array([0.65194955, 0.33027827, 0.86039552, 0.98354666, 0.06279349])

In [80]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [81]:
np.random.rand(2,4)

array([[0.41426457, 0.59379689, 0.28627235, 0.60000208],
       [0.39308511, 0.73911847, 0.28780723, 0.11467361]])

In [82]:
np.random.randint(2,4)

3

In [ ]:
np.random.randint(2,20) # 2nd argument is exclusive and generates a random number whenevr we run it . 

6

In [90]:
np.random.randint(0,1)

0

In [91]:
np.random.randint(1,6,4)

array([4, 5, 2, 3])

In [92]:
np.random.rand(3)

array([0.11046676, 0.50123632, 0.56737526])

In [ ]:
np.random.randint(1)# generates only 0 as 1 is excluded and arg should be <=0

0

In [ ]:
np.random.randint(30,20,10) # first arg value should be always low or equal to second arg value 

ValueError: low >= high

In [116]:
np.random.randint(-30,20,10)

array([  2,   1, -22,  -5,  16,   1,   9, -27, -30,  15])

In [117]:
np.random.randint(20,30,10)

array([26, 27, 26, 25, 21, 26, 20, 26, 23, 25])

In [ ]:
np.random.randint(5,9) # generates a random number between 5 ( inclusive ) and 9(exclusive)

8

In [131]:
np.random.randint(10,21,3)

array([17, 10, 19])

In [ ]:
np.random.randint(1,12,10) # low value high 1( inclusive) and higher value 12(exclusive) and size is 10

array([10,  5,  8,  9,  2,  2,  3,  5,  3,  4])

In [136]:
np.random.randint(10,40,(10,10)) # Start(incl) - 10 , stop(exclu) -10 , size - 10 X 10 

array([[29, 27, 36, 38, 25, 13, 38, 33, 23, 16],
       [33, 36, 33, 28, 20, 16, 15, 39, 12, 23],
       [39, 30, 38, 31, 25, 19, 10, 28, 29, 22],
       [11, 22, 37, 19, 10, 17, 33, 32, 17, 12],
       [30, 29, 35, 34, 29, 37, 35, 12, 37, 33],
       [22, 35, 11, 21, 37, 23, 17, 37, 21, 14],
       [14, 33, 20, 38, 27, 29, 27, 21, 21, 13],
       [28, 33, 27, 30, 19, 11, 19, 19, 28, 17],
       [23, 26, 24, 39, 20, 23, 18, 14, 10, 21],
       [20, 29, 27, 17, 29, 16, 27, 17, 33, 25]])

In [137]:
np.random.randint(1,100,(12,12)) # start 1 (incl) stop 100(exclus) size 12 X 12 matrix

array([[44, 16, 26, 43, 44, 84,  5, 33, 35, 35, 27, 94],
       [25,  5, 24, 70, 94,  8, 50, 32, 52, 64, 29, 34],
       [37, 54, 10, 55, 85, 73, 45, 60, 75, 50, 22, 60],
       [34, 15, 96, 68, 51, 12, 92, 94, 33, 70, 38, 25],
       [27, 67,  8, 40, 28,  1, 86,  1, 99, 31, 37, 51],
       [ 6,  4, 56,  5, 60, 58, 57, 11, 20, 86, 69, 86],
       [37, 19, 42, 65, 85, 47,  1, 11, 25, 96, 44, 10],
       [ 8, 35, 71, 86, 88,  9, 37, 16, 11, 55, 66, 75],
       [57, 49, 63, 74, 50, 89, 84, 38,  5, 76, 59, 87],
       [19, 44, 13, 20,  2, 26, 30, 23, 94, 12, 77, 54],
       [48, 98, 45, 84, 34, 50,  5, 36, 93, 42, 34, 84],
       [52, 86, 38,  8, 73, 19, 62, 45, 77, 27,  6, 24]])

In [ ]:
np.random.randint(1,100).reshape(12,12) # reshape doesn;t work here 

AttributeError: 'int' object has no attribute 'reshape'

In [ ]:
np.arange(1,13).reshape(3,4) # generates a 3 x 4 matrix. 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [143]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [ ]:
b = np.random.randint(10,20,(5,4)) # generates a 5 X 4 matrix and stores it in b 
b

array([[11, 13, 17, 10],
       [16, 14, 10, 16],
       [13, 18, 15, 15],
       [18, 18, 14, 19],
       [19, 11, 17, 10]])

In [ ]:
type(b) # prints the type of b 

numpy.ndarray

In [ ]:
b # displays p 

array([[11, 13, 17, 10],
       [16, 14, 10, 16],
       [13, 18, 15, 15],
       [18, 18, 14, 19],
       [19, 11, 17, 10]])

In [ ]:
b[:] # slicing works same like list 

array([[11, 13, 17, 10],
       [16, 14, 10, 16],
       [13, 18, 15, 15],
       [18, 18, 14, 19],
       [19, 11, 17, 10]])

In [ ]:
b[1:3]

array([[16, 14, 10, 16],
       [13, 18, 15, 15]])

In [149]:
b

array([[11, 13, 17, 10],
       [16, 14, 10, 16],
       [13, 18, 15, 15],
       [18, 18, 14, 19],
       [19, 11, 17, 10]])

In [ ]:
b[1,2] # displays value of row index 1 and column index 2 

np.int64(10)

In [151]:
b

array([[11, 13, 17, 10],
       [16, 14, 10, 16],
       [13, 18, 15, 15],
       [18, 18, 14, 19],
       [19, 11, 17, 10]])

In [152]:
b[1,3]

np.int64(16)

In [153]:
b[1,-1]

np.int64(16)

In [154]:
b 

array([[11, 13, 17, 10],
       [16, 14, 10, 16],
       [13, 18, 15, 15],
       [18, 18, 14, 19],
       [19, 11, 17, 10]])

In [155]:
b[2:3]

array([[13, 18, 15, 15]])

In [156]:
b 

array([[11, 13, 17, 10],
       [16, 14, 10, 16],
       [13, 18, 15, 15],
       [18, 18, 14, 19],
       [19, 11, 17, 10]])

In [157]:
b[0:-2] # prints starting from 0 index to -2( exlcusive)

array([[11, 13, 17, 10],
       [16, 14, 10, 16],
       [13, 18, 15, 15]])

In [158]:
b[0,2]

np.int64(17)

In [159]:
b

array([[11, 13, 17, 10],
       [16, 14, 10, 16],
       [13, 18, 15, 15],
       [18, 18, 14, 19],
       [19, 11, 17, 10]])

In [160]:
b[-5,-3]

np.int64(13)

In [161]:
b

array([[11, 13, 17, 10],
       [16, 14, 10, 16],
       [13, 18, 15, 15],
       [18, 18, 14, 19],
       [19, 11, 17, 10]])

In [162]:
b[-4,2]

np.int64(10)

In [163]:
np.random.randint(10,20,(4,4))

array([[10, 19, 17, 15],
       [16, 11, 14, 18],
       [14, 13, 14, 18],
       [14, 19, 19, 12]])

In [164]:
b

array([[11, 13, 17, 10],
       [16, 14, 10, 16],
       [13, 18, 15, 15],
       [18, 18, 14, 19],
       [19, 11, 17, 10]])

In [165]:
b[-4,-2]

np.int64(10)

In [166]:
b

array([[11, 13, 17, 10],
       [16, 14, 10, 16],
       [13, 18, 15, 15],
       [18, 18, 14, 19],
       [19, 11, 17, 10]])

In [167]:
b[-4:2]

array([[16, 14, 10, 16]])

In [168]:
b[:]

array([[11, 13, 17, 10],
       [16, 14, 10, 16],
       [13, 18, 15, 15],
       [18, 18, 14, 19],
       [19, 11, 17, 10]])

# Operations 

In [175]:
a = np.random.randint(10,20,10)
a 

array([14, 12, 15, 14, 18, 16, 14, 14, 17, 15])

In [ ]:
id(a) # location changes when ever a values changes. 

4806478896

In [177]:
arr

array([0, 1, 2, 3, 4, 5])

In [178]:
arr2 = np.random.randint(0,100,(10,10))

In [179]:
arr2 

array([[24, 16, 19, 29, 48,  5, 80,  6, 45, 35],
       [25, 12, 81, 36, 59, 36, 13,  4,  4, 48],
       [98,  6, 67, 17, 16, 52, 86, 61, 75, 56],
       [32, 34, 81, 65, 47, 77, 79, 43, 57, 63],
       [49, 64,  1, 94, 68, 32, 27, 45,  7, 49],
       [36, 25, 83, 56, 76, 61, 79, 92, 17,  7],
       [46, 50, 45, 60, 73, 68, 92, 16, 48, 13],
       [39, 32, 13, 30, 86, 70, 56, 71,  8, 90],
       [99, 64, 26, 23, 53, 13, 53, 22, 33, 10],
       [51, 10, 23, 76, 43,  3, 28, 84,  0, 57]])

In [180]:
arr 

array([0, 1, 2, 3, 4, 5])

In [181]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [182]:
arr

array([0, 1, 2, 3, 4, 5])

In [183]:
arr[:4]

array([0, 1, 2, 3])

In [184]:
arr2[:]

array([[24, 16, 19, 29, 48,  5, 80,  6, 45, 35],
       [25, 12, 81, 36, 59, 36, 13,  4,  4, 48],
       [98,  6, 67, 17, 16, 52, 86, 61, 75, 56],
       [32, 34, 81, 65, 47, 77, 79, 43, 57, 63],
       [49, 64,  1, 94, 68, 32, 27, 45,  7, 49],
       [36, 25, 83, 56, 76, 61, 79, 92, 17,  7],
       [46, 50, 45, 60, 73, 68, 92, 16, 48, 13],
       [39, 32, 13, 30, 86, 70, 56, 71,  8, 90],
       [99, 64, 26, 23, 53, 13, 53, 22, 33, 10],
       [51, 10, 23, 76, 43,  3, 28, 84,  0, 57]])

In [185]:
arr2[0:5]

array([[24, 16, 19, 29, 48,  5, 80,  6, 45, 35],
       [25, 12, 81, 36, 59, 36, 13,  4,  4, 48],
       [98,  6, 67, 17, 16, 52, 86, 61, 75, 56],
       [32, 34, 81, 65, 47, 77, 79, 43, 57, 63],
       [49, 64,  1, 94, 68, 32, 27, 45,  7, 49]])

In [186]:
arr2

array([[24, 16, 19, 29, 48,  5, 80,  6, 45, 35],
       [25, 12, 81, 36, 59, 36, 13,  4,  4, 48],
       [98,  6, 67, 17, 16, 52, 86, 61, 75, 56],
       [32, 34, 81, 65, 47, 77, 79, 43, 57, 63],
       [49, 64,  1, 94, 68, 32, 27, 45,  7, 49],
       [36, 25, 83, 56, 76, 61, 79, 92, 17,  7],
       [46, 50, 45, 60, 73, 68, 92, 16, 48, 13],
       [39, 32, 13, 30, 86, 70, 56, 71,  8, 90],
       [99, 64, 26, 23, 53, 13, 53, 22, 33, 10],
       [51, 10, 23, 76, 43,  3, 28, 84,  0, 57]])

In [187]:
arr2[1,4]

np.int64(59)

In [188]:
arr2 

array([[24, 16, 19, 29, 48,  5, 80,  6, 45, 35],
       [25, 12, 81, 36, 59, 36, 13,  4,  4, 48],
       [98,  6, 67, 17, 16, 52, 86, 61, 75, 56],
       [32, 34, 81, 65, 47, 77, 79, 43, 57, 63],
       [49, 64,  1, 94, 68, 32, 27, 45,  7, 49],
       [36, 25, 83, 56, 76, 61, 79, 92, 17,  7],
       [46, 50, 45, 60, 73, 68, 92, 16, 48, 13],
       [39, 32, 13, 30, 86, 70, 56, 71,  8, 90],
       [99, 64, 26, 23, 53, 13, 53, 22, 33, 10],
       [51, 10, 23, 76, 43,  3, 28, 84,  0, 57]])

In [189]:
arr2[1,4]

np.int64(59)

In [190]:
arr2 

array([[24, 16, 19, 29, 48,  5, 80,  6, 45, 35],
       [25, 12, 81, 36, 59, 36, 13,  4,  4, 48],
       [98,  6, 67, 17, 16, 52, 86, 61, 75, 56],
       [32, 34, 81, 65, 47, 77, 79, 43, 57, 63],
       [49, 64,  1, 94, 68, 32, 27, 45,  7, 49],
       [36, 25, 83, 56, 76, 61, 79, 92, 17,  7],
       [46, 50, 45, 60, 73, 68, 92, 16, 48, 13],
       [39, 32, 13, 30, 86, 70, 56, 71,  8, 90],
       [99, 64, 26, 23, 53, 13, 53, 22, 33, 10],
       [51, 10, 23, 76, 43,  3, 28, 84,  0, 57]])

In [ ]:
arr2[-5,5]

61


In [193]:
arr2[-5,-5]

np.int64(61)

In [194]:
arr2 

array([[24, 16, 19, 29, 48,  5, 80,  6, 45, 35],
       [25, 12, 81, 36, 59, 36, 13,  4,  4, 48],
       [98,  6, 67, 17, 16, 52, 86, 61, 75, 56],
       [32, 34, 81, 65, 47, 77, 79, 43, 57, 63],
       [49, 64,  1, 94, 68, 32, 27, 45,  7, 49],
       [36, 25, 83, 56, 76, 61, 79, 92, 17,  7],
       [46, 50, 45, 60, 73, 68, 92, 16, 48, 13],
       [39, 32, 13, 30, 86, 70, 56, 71,  8, 90],
       [99, 64, 26, 23, 53, 13, 53, 22, 33, 10],
       [51, 10, 23, 76, 43,  3, 28, 84,  0, 57]])

In [195]:
arr2[-5,-5]

np.int64(61)

In [197]:
arr2 

array([[24, 16, 19, 29, 48,  5, 80,  6, 45, 35],
       [25, 12, 81, 36, 59, 36, 13,  4,  4, 48],
       [98,  6, 67, 17, 16, 52, 86, 61, 75, 56],
       [32, 34, 81, 65, 47, 77, 79, 43, 57, 63],
       [49, 64,  1, 94, 68, 32, 27, 45,  7, 49],
       [36, 25, 83, 56, 76, 61, 79, 92, 17,  7],
       [46, 50, 45, 60, 73, 68, 92, 16, 48, 13],
       [39, 32, 13, 30, 86, 70, 56, 71,  8, 90],
       [99, 64, 26, 23, 53, 13, 53, 22, 33, 10],
       [51, 10, 23, 76, 43,  3, 28, 84,  0, 57]])

In [198]:
arr2[-1,-2]

np.int64(0)

In [199]:
arr2 

array([[24, 16, 19, 29, 48,  5, 80,  6, 45, 35],
       [25, 12, 81, 36, 59, 36, 13,  4,  4, 48],
       [98,  6, 67, 17, 16, 52, 86, 61, 75, 56],
       [32, 34, 81, 65, 47, 77, 79, 43, 57, 63],
       [49, 64,  1, 94, 68, 32, 27, 45,  7, 49],
       [36, 25, 83, 56, 76, 61, 79, 92, 17,  7],
       [46, 50, 45, 60, 73, 68, 92, 16, 48, 13],
       [39, 32, 13, 30, 86, 70, 56, 71,  8, 90],
       [99, 64, 26, 23, 53, 13, 53, 22, 33, 10],
       [51, 10, 23, 76, 43,  3, 28, 84,  0, 57]])

In [200]:
arr2 

array([[24, 16, 19, 29, 48,  5, 80,  6, 45, 35],
       [25, 12, 81, 36, 59, 36, 13,  4,  4, 48],
       [98,  6, 67, 17, 16, 52, 86, 61, 75, 56],
       [32, 34, 81, 65, 47, 77, 79, 43, 57, 63],
       [49, 64,  1, 94, 68, 32, 27, 45,  7, 49],
       [36, 25, 83, 56, 76, 61, 79, 92, 17,  7],
       [46, 50, 45, 60, 73, 68, 92, 16, 48, 13],
       [39, 32, 13, 30, 86, 70, 56, 71,  8, 90],
       [99, 64, 26, 23, 53, 13, 53, 22, 33, 10],
       [51, 10, 23, 76, 43,  3, 28, 84,  0, 57]])

In [201]:
arr2[::-1]

array([[51, 10, 23, 76, 43,  3, 28, 84,  0, 57],
       [99, 64, 26, 23, 53, 13, 53, 22, 33, 10],
       [39, 32, 13, 30, 86, 70, 56, 71,  8, 90],
       [46, 50, 45, 60, 73, 68, 92, 16, 48, 13],
       [36, 25, 83, 56, 76, 61, 79, 92, 17,  7],
       [49, 64,  1, 94, 68, 32, 27, 45,  7, 49],
       [32, 34, 81, 65, 47, 77, 79, 43, 57, 63],
       [98,  6, 67, 17, 16, 52, 86, 61, 75, 56],
       [25, 12, 81, 36, 59, 36, 13,  4,  4, 48],
       [24, 16, 19, 29, 48,  5, 80,  6, 45, 35]])

In [202]:
arr2

array([[24, 16, 19, 29, 48,  5, 80,  6, 45, 35],
       [25, 12, 81, 36, 59, 36, 13,  4,  4, 48],
       [98,  6, 67, 17, 16, 52, 86, 61, 75, 56],
       [32, 34, 81, 65, 47, 77, 79, 43, 57, 63],
       [49, 64,  1, 94, 68, 32, 27, 45,  7, 49],
       [36, 25, 83, 56, 76, 61, 79, 92, 17,  7],
       [46, 50, 45, 60, 73, 68, 92, 16, 48, 13],
       [39, 32, 13, 30, 86, 70, 56, 71,  8, 90],
       [99, 64, 26, 23, 53, 13, 53, 22, 33, 10],
       [51, 10, 23, 76, 43,  3, 28, 84,  0, 57]])

In [ ]:
arr2[::-2] # Step -2 

array([[51, 10, 23, 76, 43,  3, 28, 84,  0, 57],
       [39, 32, 13, 30, 86, 70, 56, 71,  8, 90],
       [36, 25, 83, 56, 76, 61, 79, 92, 17,  7],
       [32, 34, 81, 65, 47, 77, 79, 43, 57, 63],
       [25, 12, 81, 36, 59, 36, 13,  4,  4, 48]])

In [204]:
arr2 

array([[24, 16, 19, 29, 48,  5, 80,  6, 45, 35],
       [25, 12, 81, 36, 59, 36, 13,  4,  4, 48],
       [98,  6, 67, 17, 16, 52, 86, 61, 75, 56],
       [32, 34, 81, 65, 47, 77, 79, 43, 57, 63],
       [49, 64,  1, 94, 68, 32, 27, 45,  7, 49],
       [36, 25, 83, 56, 76, 61, 79, 92, 17,  7],
       [46, 50, 45, 60, 73, 68, 92, 16, 48, 13],
       [39, 32, 13, 30, 86, 70, 56, 71,  8, 90],
       [99, 64, 26, 23, 53, 13, 53, 22, 33, 10],
       [51, 10, 23, 76, 43,  3, 28, 84,  0, 57]])

In [206]:
arr2[::-3] # step -3 

array([[51, 10, 23, 76, 43,  3, 28, 84,  0, 57],
       [46, 50, 45, 60, 73, 68, 92, 16, 48, 13],
       [32, 34, 81, 65, 47, 77, 79, 43, 57, 63],
       [24, 16, 19, 29, 48,  5, 80,  6, 45, 35]])

In [207]:
arr2 

array([[24, 16, 19, 29, 48,  5, 80,  6, 45, 35],
       [25, 12, 81, 36, 59, 36, 13,  4,  4, 48],
       [98,  6, 67, 17, 16, 52, 86, 61, 75, 56],
       [32, 34, 81, 65, 47, 77, 79, 43, 57, 63],
       [49, 64,  1, 94, 68, 32, 27, 45,  7, 49],
       [36, 25, 83, 56, 76, 61, 79, 92, 17,  7],
       [46, 50, 45, 60, 73, 68, 92, 16, 48, 13],
       [39, 32, 13, 30, 86, 70, 56, 71,  8, 90],
       [99, 64, 26, 23, 53, 13, 53, 22, 33, 10],
       [51, 10, 23, 76, 43,  3, 28, 84,  0, 57]])

In [208]:
arr2[:-3]

array([[24, 16, 19, 29, 48,  5, 80,  6, 45, 35],
       [25, 12, 81, 36, 59, 36, 13,  4,  4, 48],
       [98,  6, 67, 17, 16, 52, 86, 61, 75, 56],
       [32, 34, 81, 65, 47, 77, 79, 43, 57, 63],
       [49, 64,  1, 94, 68, 32, 27, 45,  7, 49],
       [36, 25, 83, 56, 76, 61, 79, 92, 17,  7],
       [46, 50, 45, 60, 73, 68, 92, 16, 48, 13]])

In [209]:
arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr.max() # Prints maximum value of the array

np.int64(5)

In [ ]:
arr.min() # prints minimum value of the array 

np.int64(0)

In [212]:
arr 

array([0, 1, 2, 3, 4, 5])

In [213]:
arr.mean()

np.float64(2.5)

In [214]:
arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr.median() # No median function is not there. 

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [ ]:
# How to find median of an array 
from numpy import * 
a = array([1,2,3,4,9])
median(a) # median function need to be passed separately. 

np.float64(3.0)

In [219]:
arr 

array([0, 1, 2, 3, 4, 5])

In [220]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [221]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [222]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [223]:
arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr.reshape(2,4) # elements in the array should 2 X 4 = 8 , we only have 6 

ValueError: cannot reshape array of size 6 into shape (2,4)

In [225]:
arr

array([0, 1, 2, 3, 4, 5])

In [227]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr.reshape(2,3,order = 'c') # print element in row-major order 

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr.reshape(2,3,order = 'f') # print elemnt in fortran order column - wise order 

array([[0, 2, 4],
       [1, 3, 5]])

In [ ]:
arr.reshape(2,3,order='A') # A almost give you c type output 

In [230]:
arr

array([0, 1, 2, 3, 4, 5])

In [231]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [232]:
arr.reshape(1,4)

ValueError: cannot reshape array of size 6 into shape (1,4)

In [233]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [234]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [235]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [236]:
arr.reshape(2,6)

ValueError: cannot reshape array of size 6 into shape (2,6)

In [237]:
arr.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [238]:
arr 

array([0, 1, 2, 3, 4, 5])

In [239]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

# Indexing 

In [240]:
mat = np.arange(0,100).reshape(10,10)

In [241]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [242]:
row = 4 
col = 5 

In [243]:
col 

5

In [244]:
row 

4

In [245]:
mat 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [246]:
mat[row,col]

np.int64(45)

In [247]:
mat[4,5]

np.int64(45)

In [248]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [249]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [250]:
col = 6

In [251]:
mat 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [252]:
mat[6] # by default it represt rows 

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [253]:
mat 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [254]:
# with slice 
mat[:, col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [255]:
mat 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [256]:
mat[row, :]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [257]:
mat 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [258]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [259]:
mat 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [260]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [261]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [262]:
row 

4

In [263]:
mat 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [264]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [265]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [266]:
mat[row:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [267]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [268]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [269]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [270]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [271]:
mat 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [272]:
row 

4

In [273]:
col

6

In [274]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [275]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [276]:
mat[1,4]

np.int64(14)

In [277]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [278]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [279]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [280]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [281]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [282]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [283]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [284]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [285]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [286]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [287]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [288]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [289]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [290]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [291]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [292]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [293]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [294]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [295]:
mat[:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [296]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [297]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [298]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [299]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [300]:
mat 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [301]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [302]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [303]:
mat[::-5]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [304]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [305]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [306]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [307]:
mat[2:6,2:4] # 1;5 --> only row part // 1:3 -- it indicates only column parts 

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [308]:
mat 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [309]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [310]:
mat[0,1]

np.int64(1)

In [311]:
mat[1,6]

np.int64(16)

In [312]:
mat[1:]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [313]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [314]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [315]:
mat[0:1]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [316]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [317]:
mat[3:5]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [318]:
mat[3,5]

np.int64(35)

In [319]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [320]:
mat[1:2, 2:4]

array([[12, 13]])

In [321]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [322]:
mat[2:3, 2:3]

array([[22]])

In [323]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [324]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

In [325]:
mat[3:5,2:4]

array([[32, 33],
       [42, 43]])

In [326]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [327]:
mat[2:3,4:5]

array([[24]])

# Masking

In [328]:
mat # we also called as fileter 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [329]:
id(mat)

4568714864

In [330]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [331]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [332]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [333]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [334]:
mat[mat == 50]

array([50])

In [335]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [336]:
mat == 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [337]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [340]:
a1 = mat[mat<50]
a1 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [341]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [343]:
a2 = mat[mat>50]
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [345]:
a3 = mat[mat<=50]
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [346]:
a4 = mat[mat==50]
a4

array([50])

# Sample Python programs using random
# Python program to generate OTP 

In [347]:
import random

def generate_otp(length=4):
    """Generate a numeric OTP of a specified length."""
    digits = '012345'
    otp = ''.join(random.choice(digits) for _ in range(length))
    return otp

# Example usage
otp_length = 4  # You can change this to any length you prefer
otp = generate_otp(otp_length)
print(f"Your OTP is: {otp}")

Your OTP is: 0214


In [348]:
def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

good even
good even
good even


In [349]:
def wish():
    print('good even')
wish()

wish()

wish()

good even
good even
good even


In [350]:
list1=['a','b','g',1,5]
print(list1.pop)

<built-in method pop of list object at 0x110567400>


In [351]:
x = [1, 2, 3]
y = x.copy()
x.append(4)
print(x)

[1, 2, 3, 4]
